## Home Work 1 :Introduction 

In [6]:
#Import needed files
import pandas as pd
import numpy as np

In [8]:
#Import Dataset from file
df = pd.read_csv("./laptops.csv")

FileNotFoundError: [Errno 2] No such file or directory: './laptops.csv'

In [205]:
#make a copy of the original dataframe
data=df.copy()

#inspect the data
data.head()

Unnamed: 0                                             Laptop Status  \
0           0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New   
1           1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New   
2           2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New   
3           3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New   
4           4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New   

    Brand       Model            CPU  RAM  Storage Storage type       GPU  \
0    Asus  ExpertBook  Intel Core i5    8      512          SSD       NaN   
1  Alurin          Go  Intel Celeron    8      256          SSD       NaN   
2    Asus  ExpertBook  Intel Core i3    8      256          SSD       NaN   
3     MSI      Katana  Intel Core i7   16     1000          SSD  RTX 3050   
4      HP         15S  Intel Core i5   16      512          SSD       NaN   

   Screen Touch  Final Price  
0    15.6    No      1009.00  
1    15.6    No       299.00  
2    15.6    No       789.00  
3    15.6    No      1199.00  
4    15.6    No       669.01

**Question 1:** What's the version of Pandas that you installed?

**Solution:**

In [142]:
# find the version of pandas installed

version_install=pd.__version__
print("The version of pandas installed is Pandas-{}".format(version_install))

The version of pandas installed is Pandas-2.2.2


**Quetion 2:** How many records are in the dataset?

**Solution:** 

We will use the shape method to obtain the number of rows and columns in the dataframe. The shape method returns a tuple of the number of rows and columns, so we can use the first element of the tuple to get the number of rows.

In [143]:
# Find the number of records
records=data.shape[0]
print("The data contains {} records".format(records))

The data contains 2160 records


**Question 3:** How many brands are in the dataset?

**Solution:** 

we we use the nunique method in pandas to fine the number of Brand in the dataset

In [144]:
# We will use the nunique method to fine the brands
num_brands = data['Brand'].nunique()
print("There are {} brands of laptops in the dataset".format(num_brands))


There are 27 brands of laptops in the dataset


**Question 4:**  How many columns in the dataset have missing values?

**Solution:**

In [146]:

# Find columns with missing values in the dataset we will apply the len function on the  isnull and any methods of pandas
missing_values = len(data.columns[data.isnull().any()])
print("Columns with missing values:", missing_values)


Columns with missing values: 2


**Question 5:** What's the maximum final price of Dell notebooks in the dataset?

**Solution:**

In [147]:
#maximum final price of dell laptops
max_price=data[data.Brand=="Dell"]['Final Price'].max()
print("The maximum final price for Dell notebooks in the data is {}".format(max_price))

The maximum final price for Dell notebooks in the data is 3936.0


**Question 6:** Median value of Screen

1. Find the median value of Screen column in the dataset.
2. Next, calculate the most frequent value of the same Screen column.
3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
4. Now, calculate the median value of Screen once again. Has it changed?

**Solution :**

In [158]:
#median value of Screen column in the dataset
median_value=np.median(data[['Screen']])
print("median value of Screen column in the dataset is {} ".format(median_value))

median value of Screen column in the dataset is 15.6 


In [160]:
# Calculate the most frequent value of  the 'Screen' column
most_frequent_value = data['Screen'].mode()[0]

print("The most frequent value in the dataset is {}".format(most_frequent_value))


The most frequent value in the dataset is 15.6


In [162]:
#fillna method to fill the missing values in Screen column with the most frequent value 
data[['Screen']]=data[['Screen']].fillna(most_frequent_value)

#check to see if the values are fille correctly
data[['Screen']].isna().any()

Screen    False
dtype: bool

In [185]:
#calculate the median value of Screen once again and check if it has changed?
old_median_value=median_value
new_median_value=np.median((data['Screen']))
if old_median_value!=new_median_value:
    print("Yes, it has changed")
else:
    print("No, it has not changed")

No, it has not changed


**Question 7.** What's the sum of all the elements of the result?

1. Select all the "Innjoo" laptops from the dataset.

2. Select only columns RAM, Storage, Screen.

3. Get the underlying NumPy array. Let's call it X.

4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

5. Compute the inverse of XTX.

6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.




**Solution**:

In [186]:
#Select all the "Innjoo" laptops from the dataset.
df_innjoo=data[data.Brand=="Innjoo"]

In [187]:
#sellect "RAM","Storage", "Screen" from the data
innjoo=df_innjoo[["RAM","Storage", "Screen"]]
 

In [189]:
#Numpy array for dataframe innjoo denoted as X
X=np.array(innjoo)
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [191]:
# Compute the transpose of X
x_transpose = X.T

# Compute matrix-matrix multiplication between the transpose of X and X
XTX = np.dot(x_transpose, X)

# Print the result
print(XTX)


[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [192]:

# Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)


[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [193]:
#Create an array y with values [1100, 1300, 800, 900, 1000, 1100]
y=[1100, 1300, 800, 900, 1000, 1100]
y_arr=np.array(y)
print(y_arr)

[1100 1300  800  900 1000 1100]


In [196]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
XTX_inv_transpose = np.dot(XTX_inv, x_transpose)
w=np.dot(XTX_inv_transpose, y_arr)
print(w)

[45.58076606  0.42783519 45.29127938]


In [202]:
#sum of all the elements of the result
sum_w= w.sum()
print("sum of all the elements of the w is : {:.2f}".format(sum_w))

sum of all the elements of the w is : 91.30
